#!/usr/bin/env python3
"""manifest — generate the mechanical half of a repo's CLAUDE.md from source.

Living-spec tool (msdmd family). It derives *observable* facts about a repo —
package metadata (name, version, description, license, authors, repository,
build backend, development status, supported Python versions, keywords, runtime
dependencies, optional extras), plus tree facts (top-level layout, CI
workflows) — directly from `pyproject.toml` and the file tree, and splices them
into a marked, machine-owned block in CLAUDE.md:

    <!-- BEGIN GENERATED:manifest -->
    ...derived facts...
    <!-- END GENERATED:manifest -->

Everything *outside* that block stays hand-authored (the judgement: why a
boundary exists, scope, claim status, gotchas). The block is treated like a
lockfile: never hand-edited, regenerated by tooling, and a CI `--check` fails
the build when it drifts from the code.

It only derives facts it can read with confidence; anything genuinely absent
renders as `hmmm` (a visible gap to fix at the source), never a guess. Fuzzy
inference (e.g. the exact test command) is intentionally left to hand-authored
prose rather than risk emitting a wrong "fact". If the pyproject itself is
missing or unparseable, the tool fails loudly rather than emit an all-`hmmm`
block.

Stdlib only (msdmd ethos). Requires Python 3.11+ to run because it uses
`tomllib`; it is a dev/CI tool and is never shipped inside any package.

Usage (exactly one mode is required):
    python generate.py --print                       # show the block, no writes
    python generate.py --write                       # splice/refresh the block
    python generate.py --check                       # exit 1 if the block is stale
    python generate.py --root . --file CLAUDE.md --pyproject backend/pyproject.toml --write
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    tomllib = None

BEGIN = "<!-- BEGIN GENERATED:manifest -->"
END = "<!-- END GENERATED:manifest -->"
HMMM = "hmmm"  # never guess an unknown fact; surface it as a visible gap

# Directories that are noise rather than structure.
SKIP_DIRS = {
    ".git", ".github", "__pycache__", ".mypy_cache", ".ruff_cache",
    ".pytest_cache", "node_modules", ".venv", "venv", "dist", "build",
    ".idea", ".vscode", ".agents",
}


class ManifestError(Exception):
    """Raised for unrecoverable conditions (unreadable source, broken markers)."""


def _refresh_cmd(args: argparse.Namespace) -> str:
    """The exact command to regenerate this block, including non-default args."""
    parts = ["python .agents/skills/manifest/generate.py"]
    if args.root != ".":
        parts.append(f"--root {args.root}")
    if args.file != "CLAUDE.md":
        parts.append(f"--file {args.file}")
    if args.pyproject != "pyproject.toml":
        parts.append(f"--pyproject {args.pyproject}")
    parts.append("--write")
    return " ".join(parts)


def _load_pyproject(path: Path) -> dict:
    """Parse pyproject; raise ManifestError if missing or invalid (never silent)."""
    if not path.exists():
        raise ManifestError(f"pyproject not found: {path}")
    try:
        with path.open("rb") as fh:
            return tomllib.load(fh)
    except (OSError, tomllib.TOMLDecodeError) as exc:
        raise ManifestError(f"could not parse {path}: {exc}") from exc


def _top_dirs(root: Path) -> list[str]:
    out = []
    for p in sorted(root.iterdir()):
        if not p.is_dir():
            continue
        if p.name in SKIP_DIRS or p.name.startswith(".") or p.name.endswith(".egg-info"):
            continue
        out.append(p.name + "/")
    return out


def _ci_workflows(root: Path) -> list[str]:
    wf = root / ".github" / "workflows"
    if not wf.is_dir():
        return []
    return sorted(p.name for p in wf.iterdir() if p.suffix in (".yml", ".yaml"))


def _authors(proj: dict) -> list[str]:
    out = []
    for a in proj.get("authors") or []:
        name, email = a.get("name"), a.get("email")
        if name and email:
            out.append(f"{name} <{email}>")
        elif name:
            out.append(name)
        elif email:
            out.append(email)
    return out


def _repository(urls: dict) -> str | None:
    low = {k.lower(): v for k, v in urls.items()}
    for key in ("repository", "source", "homepage"):
        if key in low:
            return low[key]
    return None


def _dev_status(classifiers: list[str]) -> str | None:
    for c in classifiers:
        if c.startswith("Development Status :: "):
            return c.split("Development Status :: ", 1)[1]
    return None


def _py_versions(classifiers: list[str]) -> list[str]:
    out = []
    for c in classifiers:
        m = re.match(r"Programming Language :: Python :: (\d+\.\d+)$", c)
        if m:
            out.append(m.group(1))
    return out


def derive_facts(root: Path, pyproject_rel: str) -> dict:
    data = _load_pyproject(root / pyproject_rel)
    proj = data.get("project", {})
    classifiers = list(proj.get("classifiers") or [])

    lic = proj.get("license")
    if isinstance(lic, dict):
        lic = lic.get("text") or lic.get("file") or HMMM

    return {
        "name": proj.get("name", HMMM),
        "version": proj.get("version", HMMM),
        "description": proj.get("description", HMMM),
        "requires_python": proj.get("requires-python", HMMM),
        "license": lic or HMMM,
        "authors": _authors(proj),
        "repository": _repository(proj.get("urls") or {}),
        "build_backend": data.get("build-system", {}).get("build-backend"),
        "dev_status": _dev_status(classifiers),
        "py_versions": _py_versions(classifiers),
        "keywords": list(proj.get("keywords") or []),
        "dependencies": list(proj.get("dependencies") or []),
        "extras": sorted((proj.get("optional-dependencies") or {}).keys()),
        "pyproject": pyproject_rel,
        "dirs": _top_dirs(root),
        "ci_workflows": _ci_workflows(root),
    }


def _cell(value: str) -> str:
    """Make a value safe for a one-line markdown table cell."""
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def _scalar(value) -> str:
    return _cell(value) if value else HMMM


def _joined(items: list[str], code: bool = False, empty: str = "none") -> str:
    if not items:
        return empty
    return ", ".join(f"`{_cell(i)}`" for i in items) if code else ", ".join(_cell(i) for i in items)


def render(facts: dict, refresh_cmd: str) -> str:
    note = (
        f"<!-- Generated from pyproject + repo tree by "
        f".agents/skills/manifest/generate.py — DO NOT EDIT BY HAND. "
        f"Refresh with `{refresh_cmd}`. -->"
    )
    py = _scalar(facts["requires_python"])
    if facts["py_versions"]:
        py += f" (classifiers: {', '.join(facts['py_versions'])})"

    rows = [
        ("Package", f"`{_scalar(facts['name'])}`"),
        ("Version", f"`{_scalar(facts['version'])}`"),
        ("Description", _scalar(facts["description"])),
        ("Status", _scalar(facts["dev_status"])),
        ("Python", py),
        ("License", _scalar(facts["license"])),
        ("Build backend", f"`{_cell(facts['build_backend'])}`" if facts["build_backend"] else HMMM),
        ("Author(s)", "; ".join(_cell(a) for a in facts["authors"]) or HMMM),
        ("Repository", _scalar(facts["repository"])),
        ("Runtime dependencies", _joined(facts["dependencies"], code=True, empty="none (stdlib only)")),
        ("Optional extras", _joined(facts["extras"], code=True)),
        ("Keywords", _joined(facts["keywords"])),
        ("CI workflows", _joined(facts["ci_workflows"], code=True)),
        ("Top-level directories", " · ".join(f"`{d}`" for d in facts["dirs"]) or HMMM),
    ]

    lines = [BEGIN, note, "", "| Field | Value |", "|---|---|"]
    lines += [f"| {label} | {value} |" for label, value in rows]
    lines += [
        "",
        f"<sub>Derived from `{facts['pyproject']}` + the repo tree. "
        f"Unknown fields surface as `{HMMM}` rather than a guess.</sub>",
        END,
    ]
    return "\n".join(lines)


def splice(text: str, block: str) -> str:
    """Replace an existing manifest block, or append one if none is present.

    Fails loudly on a malformed doc (only one marker, or duplicates) so a broken
    block is repaired rather than silently compounded by a second one.
    """
    n_begin, n_end = text.count(BEGIN), text.count(END)
    if n_begin != n_end or n_begin > 1:
        raise ManifestError(
            f"malformed manifest markers in document ({n_begin}x BEGIN, {n_end}x END); "
            "repair the file so it has exactly one matched pair (or none)."
        )
    if n_begin == 1:
        pre = text.split(BEGIN, 1)[0]
        post = text.split(END, 1)[1]
        return pre + block + post
    if not text:
        return block + "\n"
    sep = "" if text.endswith("\n") else "\n"
    return text + sep + "\n" + block + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="repo root (default: .)")
    ap.add_argument("--file", default="CLAUDE.md", help="doc to splice, relative to root")
    ap.add_argument("--pyproject", default="pyproject.toml", help="pyproject path, relative to root")
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true", help="splice/refresh the block in place")
    mode.add_argument("--check", action="store_true", help="exit 1 if the block is stale")
    mode.add_argument("--print", dest="do_print", action="store_true", help="print the block to stdout")
    args = ap.parse_args(argv)

    if tomllib is None:
        sys.stderr.write("[manifest] needs Python 3.11+ (tomllib) to read pyproject.toml\n")
        return 2

    root = Path(args.root).resolve()
    if not root.is_dir():
        sys.stderr.write(f"[manifest] --root is not a directory: {root}\n")
        return 2
    refresh_cmd = _refresh_cmd(args)
    try:
        block = render(derive_facts(root, args.pyproject), refresh_cmd)
    except ManifestError as exc:
        sys.stderr.write(f"[manifest] {exc}\n")
        return 2

    if args.do_print:
        print(block)
        return 0

    doc = root / args.file
    current = doc.read_text(encoding="utf-8") if doc.exists() else ""
    try:
        updated = splice(current, block)
    except ManifestError as exc:
        sys.stderr.write(f"[manifest] {exc}\n")
        return 2

    if args.check:
        if current != updated:
            sys.stderr.write(
                f"[manifest] {args.file} manifest block is stale or missing.\n"
                f"           Run: {refresh_cmd}\n"
            )
            return 1
        print(f"[manifest] {args.file} manifest block is up to date.")
        return 0

    doc.write_text(updated, encoding="utf-8")
    verb = "refreshed" if BEGIN in current else "inserted"
    print(f"[manifest] {verb} manifest block in {args.file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
