#!/usr/bin/env python3
"""manifest — generate the mechanical half of a repo's CLAUDE.md from source.

Living-spec tool (msdmd family). It derives *observable* facts about a repo —
package name/version, Python floor, runtime dependencies, license, top-level
layout — directly from `pyproject.toml` and the file tree, and splices them
into a marked, machine-owned block in CLAUDE.md:

    <!-- BEGIN GENERATED:manifest -->
    ...derived facts...
    <!-- END GENERATED:manifest -->

Everything *outside* that block stays hand-authored (the judgement: why a
boundary exists, scope, claim status, gotchas). The block is treated like a
lockfile: never hand-edited, regenerated by tooling, and a CI `--check` fails
the build when it drifts from the code.

Stdlib only (msdmd ethos). Requires Python 3.11+ to run because it uses
`tomllib`; it is a dev/CI tool and is never shipped inside any package.

Usage:
    python generate.py --print                       # show the block, no writes
    python generate.py --write                       # splice/refresh the block
    python generate.py --check                       # exit 1 if the block is stale
    python generate.py --root . --file CLAUDE.md --pyproject backend/pyproject.toml
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    import tomllib
except ModuleNotFoundError:  # Python < 3.11
    tomllib = None

BEGIN = "<!-- BEGIN GENERATED:manifest -->"
END = "<!-- END GENERATED:manifest -->"
NOTE = (
    "<!-- Generated from pyproject + repo tree by "
    ".agents/skills/manifest/generate.py — DO NOT EDIT BY HAND. "
    "Refresh with `python .agents/skills/manifest/generate.py --write`. -->"
)
HMMM = "hmmm"  # never guess an unknown fact; surface it as a visible gap

# Directories that are noise rather than structure.
SKIP_DIRS = {
    ".git", ".github", "__pycache__", ".mypy_cache", ".ruff_cache",
    ".pytest_cache", "node_modules", ".venv", "venv", "dist", "build",
    ".idea", ".vscode", ".agents",
}


def _load_pyproject(path: Path) -> dict:
    if tomllib is None or not path.exists():
        return {}
    try:
        with path.open("rb") as fh:
            return tomllib.load(fh)
    except (OSError, tomllib.TOMLDecodeError):
        return {}


def _top_dirs(root: Path) -> list[str]:
    out = []
    for p in sorted(root.iterdir()):
        if not p.is_dir():
            continue
        if p.name in SKIP_DIRS or p.name.startswith(".") or p.name.endswith(".egg-info"):
            continue
        out.append(p.name + "/")
    return out


def derive_facts(root: Path, pyproject_rel: str) -> dict:
    data = _load_pyproject(root / pyproject_rel)
    proj = data.get("project", {})

    lic = proj.get("license")
    if isinstance(lic, dict):
        lic = lic.get("text") or lic.get("file") or HMMM

    return {
        "name": proj.get("name", HMMM),
        "version": proj.get("version", HMMM),
        "requires_python": proj.get("requires-python", HMMM),
        "license": lic or HMMM,
        "dependencies": list(proj.get("dependencies") or []),
        "pyproject": pyproject_rel,
        "dirs": _top_dirs(root),
    }


def render(facts: dict) -> str:
    deps = facts["dependencies"]
    deps_str = ", ".join(f"`{d}`" for d in deps) if deps else "none (stdlib only)"
    dirs_str = " · ".join(f"`{d}`" for d in facts["dirs"]) or HMMM
    return "\n".join([
        BEGIN,
        NOTE,
        "",
        f"**Package:** `{facts['name']}` &nbsp;·&nbsp; "
        f"**Version:** `{facts['version']}` &nbsp;·&nbsp; "
        f"**Python:** `{facts['requires_python']}` &nbsp;·&nbsp; "
        f"**License:** {facts['license']}",
        "",
        f"**Runtime dependencies:** {deps_str}",
        "",
        f"**Top-level directories:** {dirs_str}",
        "",
        f"<sub>Derived from `{facts['pyproject']}` + the repo tree. "
        f"Unknown fields surface as `{HMMM}` rather than a guess.</sub>",
        END,
    ])


def splice(text: str, block: str) -> str:
    """Replace an existing manifest block, or append one if none is present."""
    if BEGIN in text and END in text:
        pre = text.split(BEGIN, 1)[0]
        post = text.split(END, 1)[1]
        return pre + block + post
    sep = "" if text.endswith("\n") else "\n"
    return text + sep + "\n" + block + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".", help="repo root (default: .)")
    ap.add_argument("--file", default="CLAUDE.md", help="doc to splice, relative to root")
    ap.add_argument("--pyproject", default="pyproject.toml", help="pyproject path, relative to root")
    mode = ap.add_mutually_exclusive_group()
    mode.add_argument("--write", action="store_true", help="splice/refresh the block in place")
    mode.add_argument("--check", action="store_true", help="exit 1 if the block is stale")
    mode.add_argument("--print", dest="do_print", action="store_true", help="print the block to stdout")
    args = ap.parse_args(argv)

    if tomllib is None and not args.do_print:
        sys.stderr.write("[manifest] needs Python 3.11+ (tomllib) to read pyproject.toml\n")
        return 2

    root = Path(args.root).resolve()
    block = render(derive_facts(root, args.pyproject))

    if args.do_print:
        print(block)
        return 0

    doc = root / args.file
    current = doc.read_text(encoding="utf-8") if doc.exists() else ""
    updated = splice(current, block)

    if args.check:
        if current != updated:
            sys.stderr.write(
                f"[manifest] {args.file} manifest block is stale or missing.\n"
                f"           Run: python .agents/skills/manifest/generate.py --write\n"
            )
            return 1
        print(f"[manifest] {args.file} manifest block is up to date.")
        return 0

    doc.write_text(updated, encoding="utf-8")
    verb = "refreshed" if BEGIN in current else "inserted"
    print(f"[manifest] {verb} manifest block in {args.file}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
