# === CHECKS ===
# id: check_public_surface_is_bounded
#   proves: public_surface_exposes_only_ratified_foundations, public_surface_hides_superseded_lexical_constructors
#   call: self::test_public_surface_is_bounded
#   requires: python3
#   timeout: 5
#   mutates: none
#   cleanup: none
# === END CHECKS ===

import ucns


def test_public_surface_is_bounded() -> None:
    exported = set(ucns.__all__)
    for expected in (
        "LiftedCarrierPoint",
        "STRUCTURAL_NULL",
        "Cell",
        "Carrier",
        "support_weight",
        "StructurePolicy",
        "RetainedStructure",
        "ComparisonPolicy",
        "TraversalPolicy",
        "EvaluatorCandidate",
        "LawSuite",
        "LayerPairPolicy",
        "EnvelopePairPlan",
        "ContentAdapter",
        "ExperimentManifest",
        "CandidateDecisionPacket",
        "geometric_mean_product_candidate",
        "retained_presence_breadth_candidate",
        "EdcmMotionObservation",
        "EdcmCompletionTrace",
        "HmmmBoundary",
        "ScalarProjection",
        "AdmittedCorpusManifest",
        "FullCorpusExecutionReport",
        "FullCorpusCompletionReceipt",
        "execute_admitted_corpus",
        "issue_full_corpus_completion_receipt",
        "CarrierExperimentReport",
        "CarrierRelationship",
        "FalsifierVerdict",
        "run_v05_carrier_experiment",
        "DirectMobiusCandidateReport",
        "NativeMobiusState",
        "StructuralNullIdentity",
        "run_v06_direct_mobius_experiment",
        "RootLoopChartReport",
        "RootLoopCoverChartState",
        "run_v07_root_loop_chart_experiment",
        "FramedMobiusStripState",
        "TransverseEnvelopeState",
        "TransverseEnvelopeReport",
        "TransverseCarrierCollisionWitness",
        "run_v09_transverse_envelope_experiment",
        "CarrierCoordinateCandidate",
        "CarrierCoordinateImage",
        "CarrierCoordinateCandidateResult",
        "CarrierCoordinateAdmissibilityReport",
        "run_v010_carrier_coordinate_experiment",
        "ExactCarrierCoordinate",
        "ExactCoordinateProvenance",
        "Binary64CarrierRendering",
        "Binary64CollisionWitness",
        "ExactCoordinateBoundaryReport",
        "run_v011_exact_coordinate_boundary_experiment",
        "MarkedInitiationSeam",
        "TwistReceipt",
        "PartialInitiationAttachment",
        "PartialInitiationBoundaryReport",
        "RootVisibleProjection",
        "partial_initiation_exact_comparison_policy",
        "project_root_visible_state",
        "run_v013_partial_initiation_boundary_experiment",
        "AffineContinuityCertificate",
        "QuotientSeamCommutationCertificate",
        "FullCarrierAttachmentReport",
        "run_v015_full_carrier_attachment_experiment",
        "ObservedElementAdmission",
        "AssignmentOutcomeReceipt",
        "AssignmentAdmissionTrace",
        "AssignmentAdmissionBoundaryReport",
        "run_v016_assignment_admission_boundary_experiment",
        "OriginTermRecord",
        "GonolInitiationReceipt",
        "GonolInitiationOutcome",
        "GonolInitiationTrace",
        "GonolInitiationScopeCompletionReceipt",
        "RootLoopReturnWitness",
        "GonolInitiationBoundaryReport",
        "issue_gonol_initiation_scope_completion_receipt",
        "run_v017_gonol_initiation_boundary_experiment",
        "ExplicitCoordinateProposal",
        "AppliedGeometricAssignment",
        "GeometricAssignmentOutcome",
        "GeometricAssignmentTrace",
        "ExplicitGeometricAssignmentBoundaryReport",
        "run_v018_explicit_geometric_assignment_experiment",
        "CompleteOrderedSourceScopeBinding",
        "bind_complete_ordered_source_scope",
        "OrderedSourceCoordinate",
        "SourceCoordinateDerivation",
        "AppliedSourceCoordinateAssignment",
        "SourceCoordinateOutcome",
        "SourceCoordinateTrace",
        "SourceCoordinateBoundaryReport",
        "run_v019_source_coordinate_derivation_experiment",
        "RelationalCarrier",
        "build_relational_carrier",
        "relational_carrier_bytes",
        "XkcdLexicalFloor",
        "ClosedSurfaceGonol",
        "FloorOccurrence",
        "load_xkcd_lexical_floor",
        "official_xkcd_source_payload",
        "reconstruct_xkcd_lexical_floor",
        "replay_xkcd_lexical_floor",
    ):
        assert expected in exported

    for forbidden in (
        "UCNSObject",
        "product_character",
        "faithful_breadth",
        "multiply",
        "factor",
        "TheoremN",
        "default_evaluator",
        "canonical_policy",
        "canonical_product_character",
        "canonical_faithful_breadth",
        "TransverseCoverChartState",
        "TransverseStripReport",
        "run_v08_transverse_strip_experiment",
        "build_floor_definition_gonol",
        "build_complete_definition_layer",
        "FloorDefinitionGonol",
        "FloorDefinitionEvidence",
        "construct_xkcd_word_gonols",
    ):
        assert forbidden not in exported
