# === MODULE_BUILD ===
# id: foundations_public_surface
#   module_name: ucns public surface
#   module_kind: schema
#   summary: exports the UCNS decision registry, EDCM word-gonol, completion-motion, full-corpus execution, and bounded full-carrier attachment evidence, current foundations, and reproducible candidate-research infrastructure
#   owner: Erin Spencer
#   public_surface: option decisions, EDCM observation, completion-motion, v0.14 full-corpus execution evidence, v0.15 full-carrier attachment evidence, v0.5 carrier experiment, v0.6 native direct-Mobius candidate, v0.7 bounded root-loop cover chart, v0.9 exact-rational transverse-envelope repair, v0.10 bounded carrier-coordinate admissibility experiment, v0.11 exact-coordinate representation boundary, v0.13 partial initiation boundary, carrier, structure, policy, envelope, comparison, traversal, laboratory, layer-pairing, experiment, candidate, and bounded downstream profile names listed in __all__
#   internal_surface: none
#   auth_boundary: none
#   storage_boundary: none
#   network_boundary: none
#   user_data_boundary: none
#   admin_only: false
#   tests: tests/test_public_surface.py and all source-specific test modules
#   rollout: importable decisions, exact EDCM word-gonol observation profile, trajectory-first completion-motion evidence, fail-closed v0.14 full-corpus execution receipts, nonselecting v0.15 analytic and bounded attachment evidence, candidate-neutral v0.5 carrier experiment, nonselecting v0.6 direct-Mobius candidate, nonselecting v0.7 bounded root-loop chart, nonselecting v0.9 exact-rational transverse-envelope repair, nonselecting v0.10 bounded carrier-coordinate admissibility experiment, nonselecting v0.11 exact-coordinate representation boundary, nonselecting v0.13 partial initiation boundary, compatibility profile, and research infrastructure
#   rollback: remove completion-motion and downstream profile exports while preserving foundations and research surfaces
#   requires: ucns_option_decision_registry, edcm_word_gonol_profile, edcm_completion_motion_evidence, edcm_full_corpus_execution_gate, edcm_full_carrier_attachment_evidence, edcm_mobius_carrier_experiment, edcm_native_direct_mobius_candidate, edcm_root_loop_cover_chart_candidate, edcm_exact_rational_transverse_envelope_experiment, edcm_carrier_coordinate_admissibility_experiment, edcm_exact_coordinate_representation_boundary, edcm_partial_initiation_boundary, directed_carrier_floor, structural_cell_support_floor, structural_choice_policy_layer, retained_structure_envelope, explicit_comparison_policy_layer, cycle_safe_traversal_policy, evaluator_candidate_laboratory, retained_layer_pairing_laboratory, reproducible_witness_experiment_pipeline, first_competing_evaluator_candidate_families
#   since: 2026-07-21
#   unresolved: element-assignment law and total Structural Null relationship beyond the v0.15 analytic non-null and partial root evidence, proof-assistant formalization, circle-epicycle-disk-sphere transitions, higher-gonol composition, non-SPACE out-of-alphabet treatment, canonical structural equivalence, canonical M, canonical B, complete UCNS object
# === END MODULE_BUILD ===

# === CONTRACTS ===
# id: public_surface_exposes_only_ratified_foundations
#   given: a consumer imports ucns
#   then: ratified foundations, explicit research infrastructure, and the named bounded downstream profile are exported without implying canonical M, B, factorization, theorem, or universal arithmetic
#   class: safety
#   since: 2026-07-21
# === END CONTRACTS ===

"""UCNS foundations and option-preserving candidate research infrastructure.

No complete ``UCNSObject``, canonical product character, canonical faithful-breadth
evaluator, theorem-bearing arithmetic, or universal downstream promise is exported.
"""

from .carrier import (
    LIFTED_PERIOD,
    STRUCTURAL_NULL,
    VISIBLE_PERIOD,
    CarrierPoint,
    LiftedCarrierPoint,
    VisibleCarrierPoint,
    VisiblePoint,
    carrier_from_breadth,
    deck_translate,
    lifted_preimages,
    project,
    radius_from_breadth,
    same_lifted_position,
    same_visible_position,
)
from .structure import (
    Carrier,
    Cell,
    Structure,
    collapse,
    make_carrier,
    pair,
    prune,
    support_weight,
)
from .policy import (
    InformationLoss,
    OccurrenceGroup,
    PolicyRegistry,
    Projection,
    SetEntry,
    StructurePolicy,
    apply_policy,
    ordered_sequence_policy,
    set_policy,
    unordered_multiset_policy,
)
from .envelope import (
    ContributionStatus,
    RetainedEnvelope,
    RetainedLayer,
    RetainedStructure,
    cell_support_weight,
    make_retained_structure,
    project_layer,
)
from .comparison import (
    ComparisonMode,
    ComparisonPolicy,
    ComparisonRegistry,
    absolute_comparison_policy,
    combined_comparison_policy,
    custom_comparison_policy,
    exact_comparison_policy,
    interval_overlap_policy,
    relative_comparison_policy,
    ulp_comparison_policy,
)
from .traversal import (
    CycleDetectedError,
    CycleMode,
    FixedPointReceipt,
    ReferenceReceipt,
    TraversalBudget,
    TraversalPolicy,
    TraversalResult,
    TruncationReceipt,
    Visit,
    traverse,
)
from .laboratory import (
    CandidateComparison,
    CandidateOutput,
    EvaluationReport,
    EvaluatorCandidate,
    EvaluatorKind,
    EvaluatorRegistry,
    Law,
    LawResult,
    LawSuite,
    Witness,
    compare_candidates,
    finite_nonnegative_law,
    invariance_law,
    null_zero_law,
    pair_multiplicative_law,
    same_candidate_different_reference_law,
    same_reference_different_candidate_law,
    sensitivity_law,
)
from .layer_pairing import (
    EnvelopePairPlan,
    EnvelopePairResult,
    LayerPairDecision,
    LayerPairMode,
    LayerPairPolicy,
    LayerPairProjection,
    LayerPairRegistry,
    LayerPairRule,
    LayerRef,
    UnmatchedLayerMode,
    cartesian_layer_policy,
    concatenate_layer_policy,
    custom_layer_pair_policy,
    exclude_layer_policy,
    keep_sides_layer_policy,
    pair_retained,
    positional_zip_layer_policy,
    select_left_layer_policy,
    select_right_layer_policy,
)
from .experiments import (
    AdapterRegistry,
    AuthorshipRecord,
    CandidateDecisionPacket,
    CandidateIdentity,
    ContentAdapter,
    CorpusPartition,
    Counterexample,
    ExperimentManifest,
    ExperimentResult,
    HoldoutReport,
    LawSuiteDigest,
    MetamorphicCase,
    MutationCase,
    NamedTransform,
    PolicyDigest,
    ReproductionCheck,
    SubjectRecord,
    WitnessCase,
    WitnessCorpus,
    WitnessOrigin,
    build_candidate_decision_packet,
    bytes_content_adapter,
    check_reproduction,
    comparison_policy_digest,
    generate_metamorphic_cases,
    generate_mutation_cases,
    greedy_minimize_counterexample,
    json_content_adapter,
    text_content_adapter,
    traversal_policy_digest,
)
from .candidates import (
    CandidateScopeError,
    cell_detail_breadth_candidate,
    cell_log_support_breadth_candidate,
    exact_evidence_equivalence_candidate,
    geometric_mean_product_candidate,
    layer_scoped_equivalence_candidate,
    maximum_support_product_candidate,
    minimum_support_product_candidate,
    policy_projection_equivalence_candidate,
    retained_presence_breadth_candidate,
)
from .options import (
    OPTION_REGISTRY_SCHEMA_ID,
    OPTION_REGISTRY_SCHEMA_VERSION,
    UCNS_IDENTIFIER,
    OptionRegistryError,
    load_option_registry,
    option_dimension,
)
from .edcm import (
    EDCM_CORPUS_EXECUTION,
    EDCM_GONOL_INITIATION,
    EDCM_NORMALIZATION_POLICY,
    EDCM_PROFILE_ID,
    EDCM_PROFILE_OPTIONS,
    EDCM_PROFILE_SCOPE,
    EDCM_PROFILE_VERSION,
    EDCM_SMALLEST_GONOL,
    EDCM_SOURCE_DOMAIN,
    EDCM_SPACE_ASSIGNMENT_POLICY,
    EDCM_SPACE_CODE_POINTS,
    EDCM_SUPPORT_POLICY,
    PUBLIC_GONOL_157,
    PUBLIC_GONOL_SHA256,
    EdcmProfileError,
    EdcmTokenObservation,
    EdcmTurnObservation,
    EdcmWordGonol,
    EdcmWordGonolProfile,
    SuperpositionedSpaceBoundary,
    decode_utf8_exact,
    edcm_carrier_position,
    public_gonol_sha256,
)
from .edcm_motion import (
    EDCM_ASSIGNMENT_LAW_STATUS,
    EDCM_HIGHER_MOTION_LAW_STATUS,
    EDCM_MOTION_SCHEMA_ID,
    EDCM_MOTION_SCHEMA_VERSION,
    EDCM_MOTION_SCOPE,
    EDCM_MOTION_SELECTION_EFFECT,
    CompletionRegistration,
    CompletionState,
    EdcmCompletionTrace,
    EdcmMetricFamily,
    EdcmMotionError,
    EdcmMotionObservation,
    EpicyclicParentage,
    EvidenceStatus,
    GeometricAssignment,
    GeometryKind,
    HmmmBoundary,
    LawStanding,
    MotionStep,
    ObservedElement,
    ScalarProjection,
    SourceProvenance,
    record_word_motion,
)
from .full_corpus import (
    POST_RUN_GATE_CLOSED,
    POST_RUN_GATE_OPEN,
    V014_FULL_CORPUS_EDCM_ACTIVATION,
    V014_FULL_CORPUS_METAPAT_ACTIVATION,
    V014_FULL_CORPUS_SCHEMA_ID,
    V014_FULL_CORPUS_SCHEMA_VERSION,
    V014_FULL_CORPUS_SELECTION_EFFECT,
    AdmittedCorpusManifest,
    CorpusAdapterIdentity,
    CorpusRunFailure,
    CorpusRunFailureKind,
    CorpusRunStatus,
    FullCorpusCompletionReceipt,
    FullCorpusError,
    FullCorpusExecutionReport,
    execute_admitted_corpus,
    issue_full_corpus_completion_receipt,
)
from .mobius_experiment import (
    BREADTH_CANDIDATE_IDS,
    FALSIFIER_IDS,
    MINIMUM_WITNESS_TEXTS,
    PRODUCT_CANDIDATE_IDS,
    REQUIRED_COMMUTATION_LABELS,
    REQUIRED_MAP_DISTINCTIONS,
    V05_EXPERIMENT_SCHEMA_ID,
    V05_EXPERIMENT_SCHEMA_VERSION,
    V05_SELECTION_EFFECT,
    CandidateTrace,
    CarrierExperimentError,
    CarrierExperimentReport,
    CarrierExperimentState,
    CarrierMapEvidence,
    CarrierRelationship,
    FalsifierResult,
    FalsifierVerdict,
    MapCommutationWitness,
    MetricDisplay,
    SeparatingWitness,
    SourceWitness,
    build_v05_witness_packet,
    directed_cover_trace,
    evaluate_candidate_trace,
    evaluate_chart_map,
    evaluate_separating_witness,
    run_v05_carrier_experiment,
)
from .direct_mobius import (
    NATIVE_MOBIUS_LAW_ID,
    NATIVE_MOBIUS_LAW_VERSION,
    NATIVE_MOBIUS_SCOPE,
    STRUCTURAL_NULL_ORIGIN,
    STRUCTURAL_NULL_ORIGIN_ID,
    V06_DIRECT_MOBIUS_SCHEMA_ID,
    V06_DIRECT_MOBIUS_SCHEMA_VERSION,
    V06_SELECTION_EFFECT,
    DirectMobiusCandidateReport,
    DirectMobiusError,
    MobiusInitiationEvent,
    NativeMobiusFrame,
    NativeMobiusInitiationPacket,
    NativeMobiusState,
    StructuralNullIdentity,
    StructuralNullKind,
    StructuralNullManifestation,
    build_native_mobius_initiation_packet,
    native_direct_mobius_trace,
    run_v06_direct_mobius_experiment,
)
from .root_loop_chart import (
    ROOT_LOOP_CHART_BREADTH,
    ROOT_LOOP_CHART_MAP_ID,
    ROOT_LOOP_CHART_MAP_VERSION,
    ROOT_LOOP_CHART_SCOPE,
    V07_ROOT_LOOP_CHART_SCHEMA_ID,
    V07_ROOT_LOOP_CHART_SCHEMA_VERSION,
    V07_SELECTION_EFFECT,
    RootLoopChartError,
    RootLoopChartReport,
    RootLoopChartRoundTrip,
    RootLoopCoverChartState,
    build_root_loop_chart_evidence,
    build_root_loop_chart_round_trips,
    mobius_to_root_loop_cover,
    root_loop_cover_to_mobius,
    run_v07_root_loop_chart_experiment,
)
from .transverse_envelope import (
    TRANSVERSE_BOUND,
    TRANSVERSE_CARRIER_MAPPING_STATUS,
    TRANSVERSE_COMPARISON_POLICY_CODE_REFERENCE,
    TRANSVERSE_COMPARISON_POLICY_NAME,
    TRANSVERSE_COMPARISON_POLICY_VERSION,
    TRANSVERSE_ENVELOPE_ADAPTER_ID,
    TRANSVERSE_ENVELOPE_ADAPTER_VERSION,
    TRANSVERSE_ENVELOPE_SCOPE,
    TRANSVERSE_STRESS_MAX_DENOMINATOR,
    TRANSVERSE_TRANSITION_LABELS,
    V09_SELECTION_EFFECT,
    V09_TRANSVERSE_ENVELOPE_SCHEMA_ID,
    V09_TRANSVERSE_ENVELOPE_SCHEMA_VERSION,
    ConventionMotionWitness,
    ConventionRoundTripWitness,
    FramedMobiusStripState,
    RootLoopRestrictionWitness,
    TransverseCarrierCollisionWitness,
    TransverseCoordinateConvention,
    TransverseEnvelopeError,
    TransverseEnvelopeReport,
    TransverseEnvelopeRoundTrip,
    TransverseEnvelopeState,
    TransverseMotionWitness,
    build_convention_motion_witnesses,
    build_convention_round_trips,
    build_root_loop_restrictions,
    build_transverse_carrier_collisions,
    build_transverse_motion_witnesses,
    build_transverse_round_trips,
    convert_transverse_convention,
    exact_rational_stress_fibers,
    mobius_to_transverse_envelope,
    run_v09_transverse_envelope_experiment,
    transverse_envelope_to_mobius,
    transverse_exact_comparison_policy,
)
from .carrier_coordinate import (
    CARRIER_COORDINATE_CANDIDATE_VERSION,
    CARRIER_COORDINATE_CODE_REFERENCE,
    CARRIER_COORDINATE_COMPARISON_POLICY_CODE_REFERENCE,
    CARRIER_COORDINATE_COMPARISON_POLICY_NAME,
    CARRIER_COORDINATE_COMPARISON_POLICY_VERSION,
    CARRIER_COORDINATE_RADIAL_SCALE,
    CARRIER_COORDINATE_ROOT_BREADTH,
    CARRIER_COORDINATE_SCOPE,
    V010_CARRIER_COORDINATE_SCHEMA_ID,
    V010_CARRIER_COORDINATE_SCHEMA_VERSION,
    V010_SELECTION_EFFECT,
    CarrierCoordinateAdmissibility,
    CarrierCoordinateAdmissibilityReport,
    CarrierCoordinateBasis,
    CarrierCoordinateCandidate,
    CarrierCoordinateCandidateResult,
    CarrierCoordinateCollisionWitness,
    CarrierCoordinateConventionWitness,
    CarrierCoordinateError,
    CarrierCoordinateImage,
    CarrierCoordinateMotionWitness,
    CarrierCoordinateRootRestrictionWitness,
    carrier_coordinate_candidates,
    carrier_coordinate_exact_comparison_policy,
    map_transverse_to_actual_cover,
    run_v010_carrier_coordinate_experiment,
)
from .exact_coordinate import (
    BINARY64_COORDINATE_STATUS,
    BINARY64_RENDERING_STATUS,
    EXACT_COORDINATE_CANDIDATE_ID,
    EXACT_COORDINATE_CODE_REFERENCE,
    EXACT_COORDINATE_FORMULA,
    EXACT_COORDINATE_LAW_ID,
    EXACT_COORDINATE_LAW_STATUS,
    EXACT_COORDINATE_LAW_VERSION,
    EXACT_COORDINATE_RENDERING_CODE_REFERENCE,
    EXACT_COORDINATE_RENDERING_POLICY_ID,
    EXACT_COORDINATE_RENDERING_POLICY_VERSION,
    EXACT_COORDINATE_SCOPE,
    EXACT_COORDINATE_STATUS,
    V011_EXACT_COORDINATE_SCHEMA_ID,
    V011_EXACT_COORDINATE_SCHEMA_VERSION,
    V011_SELECTION_EFFECT,
    Binary64CarrierRendering,
    Binary64CollisionKind,
    Binary64CollisionWitness,
    ExactCarrierCoordinate,
    ExactCoordinateBoundaryReport,
    ExactCoordinateError,
    ExactCoordinateProvenance,
    binary64_collision_witnesses,
    recover_signed_local_transverse,
    render_exact_coordinate_binary64,
    run_v011_exact_coordinate_boundary_experiment,
    signed_local_exact_coordinate,
)
from .initiation_boundary import (
    MARKED_SEAM_POLICY_ID,
    MARKED_SEAM_POLICY_VERSION,
    PARTIAL_INITIATION_RELATION_ID,
    PARTIAL_INITIATION_RELATION_VERSION,
    PARTIAL_INITIATION_SCOPE,
    RC_COMPARISON_POLICY_CODE_REFERENCE,
    RC_COMPARISON_POLICY_NAME,
    RC_COMPARISON_POLICY_VERSION,
    RC_EXPECTED_VERDICTS,
    RC_FALSIFIER_IDS,
    ROOT_VISIBLE_PROJECTION_ID,
    ROOT_VISIBLE_PROJECTION_INFORMATION_LOSS,
    ROOT_VISIBLE_PROJECTION_VERSION,
    SEAM_COORDINATE_VIEW_STATUS,
    TWIST_RECEIPT_LAW_ID,
    TWIST_RECEIPT_LAW_VERSION,
    V013_COMPLETE_RELATIONSHIP_STATUS,
    V013_COORDINATE_COMPONENT_STATUS,
    V013_HMMM,
    V013_INITIATION_BOUNDARY_SCHEMA_ID,
    V013_INITIATION_BOUNDARY_SCHEMA_VERSION,
    V013_SEAM_STATUS,
    V013_SELECTION_EFFECT,
    V013_STRUCTURAL_NULL_TOPOLOGY_STATUS,
    CarrierMotionReceipt,
    ContinuityFalsifierResult,
    InitiatedCarrierState,
    InitiationBoundaryError,
    MarkedInitiationSeam,
    PartialInitiationAttachment,
    PartialInitiationBoundaryReport,
    RootVisibleProjection,
    SeamCoordinateView,
    StructuralNullTopologyKind,
    TwistReceipt,
    advance_attached_state,
    build_partial_initiation_attachments,
    exact_sheet_involution,
    initiate_carrier_state,
    partial_initiation_exact_comparison_policy,
    project_root_visible_state,
    run_v013_partial_initiation_boundary_experiment,
    view_marked_seam_at_cut,
)
from .full_carrier_attachment import (
    AFFINE_CERTIFICATE_ID,
    AFFINE_CERTIFICATE_VERSION,
    AFFINE_FORMULA,
    AFFINE_REAL_SCOPE,
    ANALYTIC_PROOF_STATUS,
    COORDINATE_CUT_STATUS,
    NON_NULL_QUOTIENT_SCOPE,
    QUOTIENT_CERTIFICATE_ID,
    QUOTIENT_CERTIFICATE_VERSION,
    QUOTIENT_DESCENT_THEOREM,
    STRUCTURAL_NULL_ATTACHMENT_STATUS,
    STRUCTURAL_NULL_DOMAIN_STATUS,
    V015_COMPLETE_RELATIONSHIP_STATUS,
    V015_FULL_CARRIER_SCHEMA_ID,
    V015_FULL_CARRIER_SCHEMA_VERSION,
    V015_HMMM,
    V015_SELECTION_EFFECT,
    AffineContinuityCertificate,
    CarrierAttachmentEvidenceResult,
    ContinuityEvidenceStanding,
    FullCarrierAttachmentError,
    FullCarrierAttachmentReport,
    QuotientSeamCommutationCertificate,
    run_v015_full_carrier_attachment_experiment,
)
from .bridge import (
    BRIDGE_SCHEMA_ID,
    BRIDGE_SCHEMA_VERSION,
    PRODUCER_EPOCH,
    PROFILE_ID,
    PROFILE_VERSION,
    BridgeCell,
    BridgeValidationError,
    EdcmMetapatBridgeRecord,
    InformationLossRecord,
    RetainedLayerDigest,
)
from .profiles import (
    PROFILE_OPTIONS,
    EdcmMetapatOrderedOccurrenceProfile,
    ProfileBoundStructure,
)

__all__ = [
    "LIFTED_PERIOD", "STRUCTURAL_NULL", "VISIBLE_PERIOD", "CarrierPoint",
    "LiftedCarrierPoint", "VisibleCarrierPoint", "VisiblePoint",
    "carrier_from_breadth", "deck_translate", "lifted_preimages", "project",
    "radius_from_breadth", "same_lifted_position", "same_visible_position",
    "Carrier", "Cell", "Structure", "collapse", "make_carrier", "pair",
    "prune", "support_weight", "InformationLoss", "OccurrenceGroup",
    "PolicyRegistry", "Projection", "SetEntry", "StructurePolicy",
    "apply_policy", "ordered_sequence_policy", "set_policy",
    "unordered_multiset_policy", "ContributionStatus", "RetainedEnvelope",
    "RetainedLayer", "RetainedStructure", "cell_support_weight",
    "make_retained_structure", "project_layer", "ComparisonMode",
    "ComparisonPolicy", "ComparisonRegistry", "absolute_comparison_policy",
    "combined_comparison_policy", "custom_comparison_policy",
    "exact_comparison_policy", "interval_overlap_policy",
    "relative_comparison_policy", "ulp_comparison_policy",
    "CycleDetectedError", "CycleMode", "FixedPointReceipt",
    "ReferenceReceipt", "TraversalBudget", "TraversalPolicy",
    "TraversalResult", "TruncationReceipt", "Visit", "traverse",
    "CandidateComparison", "CandidateOutput", "EvaluationReport",
    "EvaluatorCandidate", "EvaluatorKind", "EvaluatorRegistry", "Law",
    "LawResult", "LawSuite", "Witness", "compare_candidates",
    "finite_nonnegative_law", "invariance_law", "null_zero_law",
    "pair_multiplicative_law", "same_candidate_different_reference_law",
    "same_reference_different_candidate_law", "sensitivity_law",
    "EnvelopePairPlan", "EnvelopePairResult", "LayerPairDecision",
    "LayerPairMode", "LayerPairPolicy", "LayerPairProjection",
    "LayerPairRegistry", "LayerPairRule", "LayerRef", "UnmatchedLayerMode",
    "cartesian_layer_policy", "concatenate_layer_policy",
    "custom_layer_pair_policy", "exclude_layer_policy",
    "keep_sides_layer_policy", "pair_retained",
    "positional_zip_layer_policy", "select_left_layer_policy",
    "select_right_layer_policy", "AdapterRegistry", "AuthorshipRecord",
    "CandidateDecisionPacket", "CandidateIdentity", "ContentAdapter",
    "CorpusPartition", "Counterexample", "ExperimentManifest",
    "ExperimentResult", "HoldoutReport", "LawSuiteDigest",
    "MetamorphicCase", "MutationCase", "NamedTransform", "PolicyDigest",
    "ReproductionCheck", "SubjectRecord", "WitnessCase", "WitnessCorpus",
    "WitnessOrigin", "build_candidate_decision_packet",
    "bytes_content_adapter", "check_reproduction",
    "comparison_policy_digest", "generate_metamorphic_cases",
    "generate_mutation_cases", "greedy_minimize_counterexample",
    "json_content_adapter", "text_content_adapter",
    "traversal_policy_digest", "CandidateScopeError",
    "cell_detail_breadth_candidate", "cell_log_support_breadth_candidate",
    "exact_evidence_equivalence_candidate",
    "geometric_mean_product_candidate", "layer_scoped_equivalence_candidate",
    "maximum_support_product_candidate", "minimum_support_product_candidate",
    "policy_projection_equivalence_candidate",
    "retained_presence_breadth_candidate",
    "OPTION_REGISTRY_SCHEMA_ID", "OPTION_REGISTRY_SCHEMA_VERSION",
    "UCNS_IDENTIFIER", "OptionRegistryError", "load_option_registry",
    "option_dimension", "EDCM_CORPUS_EXECUTION", "EDCM_GONOL_INITIATION",
    "EDCM_NORMALIZATION_POLICY", "EDCM_PROFILE_ID", "EDCM_PROFILE_OPTIONS",
    "EDCM_PROFILE_SCOPE", "EDCM_PROFILE_VERSION", "EDCM_SMALLEST_GONOL",
    "EDCM_SOURCE_DOMAIN", "EDCM_SPACE_ASSIGNMENT_POLICY",
    "EDCM_SPACE_CODE_POINTS",
    "EDCM_SUPPORT_POLICY", "PUBLIC_GONOL_157", "PUBLIC_GONOL_SHA256",
    "EdcmProfileError", "EdcmTokenObservation", "EdcmTurnObservation",
    "EdcmWordGonol", "EdcmWordGonolProfile",
    "SuperpositionedSpaceBoundary", "decode_utf8_exact",
    "edcm_carrier_position", "public_gonol_sha256",
    "EDCM_ASSIGNMENT_LAW_STATUS",
    "EDCM_HIGHER_MOTION_LAW_STATUS", "EDCM_MOTION_SCHEMA_ID",
    "EDCM_MOTION_SCHEMA_VERSION", "EDCM_MOTION_SCOPE",
    "EDCM_MOTION_SELECTION_EFFECT", "CompletionRegistration",
    "CompletionState", "EdcmCompletionTrace", "EdcmMetricFamily",
    "EdcmMotionError", "EdcmMotionObservation", "EpicyclicParentage",
    "EvidenceStatus", "GeometricAssignment", "GeometryKind", "HmmmBoundary",
    "LawStanding", "MotionStep", "ObservedElement", "ScalarProjection",
    "SourceProvenance", "record_word_motion",
    "POST_RUN_GATE_CLOSED", "POST_RUN_GATE_OPEN",
    "V014_FULL_CORPUS_EDCM_ACTIVATION",
    "V014_FULL_CORPUS_METAPAT_ACTIVATION",
    "V014_FULL_CORPUS_SCHEMA_ID", "V014_FULL_CORPUS_SCHEMA_VERSION",
    "V014_FULL_CORPUS_SELECTION_EFFECT", "AdmittedCorpusManifest",
    "CorpusAdapterIdentity", "CorpusRunFailure", "CorpusRunFailureKind",
    "CorpusRunStatus", "FullCorpusCompletionReceipt", "FullCorpusError",
    "FullCorpusExecutionReport", "execute_admitted_corpus",
    "issue_full_corpus_completion_receipt",
    "BREADTH_CANDIDATE_IDS", "FALSIFIER_IDS", "MINIMUM_WITNESS_TEXTS",
    "PRODUCT_CANDIDATE_IDS", "REQUIRED_COMMUTATION_LABELS",
    "REQUIRED_MAP_DISTINCTIONS", "V05_EXPERIMENT_SCHEMA_ID",
    "V05_EXPERIMENT_SCHEMA_VERSION", "V05_SELECTION_EFFECT",
    "CandidateTrace", "CarrierExperimentError", "CarrierExperimentReport",
    "CarrierExperimentState", "CarrierMapEvidence", "CarrierRelationship",
    "FalsifierResult", "FalsifierVerdict", "MapCommutationWitness",
    "MetricDisplay", "SeparatingWitness", "SourceWitness",
    "build_v05_witness_packet", "directed_cover_trace",
    "evaluate_candidate_trace", "evaluate_chart_map",
    "evaluate_separating_witness", "run_v05_carrier_experiment",
    "NATIVE_MOBIUS_LAW_ID", "NATIVE_MOBIUS_LAW_VERSION",
    "NATIVE_MOBIUS_SCOPE", "STRUCTURAL_NULL_ORIGIN",
    "STRUCTURAL_NULL_ORIGIN_ID", "V06_DIRECT_MOBIUS_SCHEMA_ID",
    "V06_DIRECT_MOBIUS_SCHEMA_VERSION", "V06_SELECTION_EFFECT",
    "DirectMobiusCandidateReport", "DirectMobiusError",
    "MobiusInitiationEvent", "NativeMobiusFrame",
    "NativeMobiusInitiationPacket", "NativeMobiusState",
    "StructuralNullIdentity", "StructuralNullKind",
    "StructuralNullManifestation", "build_native_mobius_initiation_packet",
    "native_direct_mobius_trace", "run_v06_direct_mobius_experiment",
    "ROOT_LOOP_CHART_BREADTH", "ROOT_LOOP_CHART_MAP_ID",
    "ROOT_LOOP_CHART_MAP_VERSION", "ROOT_LOOP_CHART_SCOPE",
    "V07_ROOT_LOOP_CHART_SCHEMA_ID", "V07_ROOT_LOOP_CHART_SCHEMA_VERSION",
    "V07_SELECTION_EFFECT", "RootLoopChartError", "RootLoopChartReport",
    "RootLoopChartRoundTrip", "RootLoopCoverChartState",
    "build_root_loop_chart_evidence", "build_root_loop_chart_round_trips",
    "mobius_to_root_loop_cover", "root_loop_cover_to_mobius",
    "run_v07_root_loop_chart_experiment",
    "TRANSVERSE_BOUND", "TRANSVERSE_CARRIER_MAPPING_STATUS",
    "TRANSVERSE_COMPARISON_POLICY_CODE_REFERENCE",
    "TRANSVERSE_COMPARISON_POLICY_NAME",
    "TRANSVERSE_COMPARISON_POLICY_VERSION",
    "TRANSVERSE_ENVELOPE_ADAPTER_ID", "TRANSVERSE_ENVELOPE_ADAPTER_VERSION",
    "TRANSVERSE_ENVELOPE_SCOPE", "TRANSVERSE_STRESS_MAX_DENOMINATOR",
    "TRANSVERSE_TRANSITION_LABELS", "V09_SELECTION_EFFECT",
    "V09_TRANSVERSE_ENVELOPE_SCHEMA_ID",
    "V09_TRANSVERSE_ENVELOPE_SCHEMA_VERSION", "ConventionMotionWitness",
    "ConventionRoundTripWitness", "FramedMobiusStripState",
    "RootLoopRestrictionWitness", "TransverseCarrierCollisionWitness",
    "TransverseCoordinateConvention", "TransverseEnvelopeError",
    "TransverseEnvelopeReport", "TransverseEnvelopeRoundTrip",
    "TransverseEnvelopeState", "TransverseMotionWitness",
    "build_convention_motion_witnesses",
    "build_convention_round_trips", "build_root_loop_restrictions",
    "build_transverse_carrier_collisions",
    "build_transverse_motion_witnesses", "build_transverse_round_trips",
    "convert_transverse_convention", "exact_rational_stress_fibers",
    "mobius_to_transverse_envelope", "run_v09_transverse_envelope_experiment",
    "transverse_envelope_to_mobius", "transverse_exact_comparison_policy",
    "CARRIER_COORDINATE_CANDIDATE_VERSION",
    "CARRIER_COORDINATE_CODE_REFERENCE",
    "CARRIER_COORDINATE_COMPARISON_POLICY_CODE_REFERENCE",
    "CARRIER_COORDINATE_COMPARISON_POLICY_NAME",
    "CARRIER_COORDINATE_COMPARISON_POLICY_VERSION",
    "CARRIER_COORDINATE_RADIAL_SCALE", "CARRIER_COORDINATE_ROOT_BREADTH",
    "CARRIER_COORDINATE_SCOPE", "V010_CARRIER_COORDINATE_SCHEMA_ID",
    "V010_CARRIER_COORDINATE_SCHEMA_VERSION", "V010_SELECTION_EFFECT",
    "CarrierCoordinateAdmissibility",
    "CarrierCoordinateAdmissibilityReport", "CarrierCoordinateBasis",
    "CarrierCoordinateCandidate", "CarrierCoordinateCandidateResult",
    "CarrierCoordinateCollisionWitness",
    "CarrierCoordinateConventionWitness", "CarrierCoordinateError",
    "CarrierCoordinateImage", "CarrierCoordinateMotionWitness",
    "CarrierCoordinateRootRestrictionWitness",
    "carrier_coordinate_candidates",
    "carrier_coordinate_exact_comparison_policy",
    "map_transverse_to_actual_cover",
    "run_v010_carrier_coordinate_experiment",
    "BINARY64_COORDINATE_STATUS", "BINARY64_RENDERING_STATUS",
    "EXACT_COORDINATE_CANDIDATE_ID",
    "EXACT_COORDINATE_CODE_REFERENCE", "EXACT_COORDINATE_FORMULA",
    "EXACT_COORDINATE_LAW_ID", "EXACT_COORDINATE_LAW_STATUS",
    "EXACT_COORDINATE_LAW_VERSION",
    "EXACT_COORDINATE_RENDERING_CODE_REFERENCE",
    "EXACT_COORDINATE_RENDERING_POLICY_ID",
    "EXACT_COORDINATE_RENDERING_POLICY_VERSION", "EXACT_COORDINATE_SCOPE",
    "EXACT_COORDINATE_STATUS", "V011_EXACT_COORDINATE_SCHEMA_ID",
    "V011_EXACT_COORDINATE_SCHEMA_VERSION", "V011_SELECTION_EFFECT",
    "Binary64CarrierRendering", "Binary64CollisionKind",
    "Binary64CollisionWitness", "ExactCarrierCoordinate",
    "ExactCoordinateBoundaryReport", "ExactCoordinateError",
    "ExactCoordinateProvenance", "binary64_collision_witnesses",
    "recover_signed_local_transverse", "render_exact_coordinate_binary64",
    "run_v011_exact_coordinate_boundary_experiment",
    "signed_local_exact_coordinate",
    "MARKED_SEAM_POLICY_ID", "MARKED_SEAM_POLICY_VERSION",
    "PARTIAL_INITIATION_RELATION_ID",
    "PARTIAL_INITIATION_RELATION_VERSION", "PARTIAL_INITIATION_SCOPE",
    "RC_COMPARISON_POLICY_CODE_REFERENCE", "RC_COMPARISON_POLICY_NAME",
    "RC_COMPARISON_POLICY_VERSION", "RC_EXPECTED_VERDICTS",
    "RC_FALSIFIER_IDS", "ROOT_VISIBLE_PROJECTION_ID",
    "ROOT_VISIBLE_PROJECTION_INFORMATION_LOSS",
    "ROOT_VISIBLE_PROJECTION_VERSION", "SEAM_COORDINATE_VIEW_STATUS",
    "TWIST_RECEIPT_LAW_ID", "TWIST_RECEIPT_LAW_VERSION",
    "V013_COMPLETE_RELATIONSHIP_STATUS",
    "V013_COORDINATE_COMPONENT_STATUS", "V013_HMMM",
    "V013_INITIATION_BOUNDARY_SCHEMA_ID",
    "V013_INITIATION_BOUNDARY_SCHEMA_VERSION", "V013_SEAM_STATUS",
    "V013_SELECTION_EFFECT", "V013_STRUCTURAL_NULL_TOPOLOGY_STATUS",
    "CarrierMotionReceipt", "ContinuityFalsifierResult",
    "InitiatedCarrierState", "InitiationBoundaryError",
    "MarkedInitiationSeam", "PartialInitiationAttachment",
    "PartialInitiationBoundaryReport", "RootVisibleProjection",
    "SeamCoordinateView",
    "StructuralNullTopologyKind", "TwistReceipt",
    "advance_attached_state", "build_partial_initiation_attachments",
    "exact_sheet_involution", "initiate_carrier_state",
    "partial_initiation_exact_comparison_policy",
    "project_root_visible_state",
    "run_v013_partial_initiation_boundary_experiment",
    "view_marked_seam_at_cut",
    "AFFINE_CERTIFICATE_ID", "AFFINE_CERTIFICATE_VERSION",
    "AFFINE_FORMULA", "AFFINE_REAL_SCOPE", "ANALYTIC_PROOF_STATUS",
    "COORDINATE_CUT_STATUS", "NON_NULL_QUOTIENT_SCOPE",
    "QUOTIENT_CERTIFICATE_ID", "QUOTIENT_CERTIFICATE_VERSION",
    "QUOTIENT_DESCENT_THEOREM", "STRUCTURAL_NULL_ATTACHMENT_STATUS",
    "STRUCTURAL_NULL_DOMAIN_STATUS", "V015_COMPLETE_RELATIONSHIP_STATUS",
    "V015_FULL_CARRIER_SCHEMA_ID", "V015_FULL_CARRIER_SCHEMA_VERSION",
    "V015_HMMM", "V015_SELECTION_EFFECT", "AffineContinuityCertificate",
    "CarrierAttachmentEvidenceResult", "ContinuityEvidenceStanding",
    "FullCarrierAttachmentError", "FullCarrierAttachmentReport",
    "QuotientSeamCommutationCertificate",
    "run_v015_full_carrier_attachment_experiment",
    "BRIDGE_SCHEMA_ID",
    "BRIDGE_SCHEMA_VERSION", "PRODUCER_EPOCH",
    "PROFILE_ID", "PROFILE_VERSION", "BridgeCell", "BridgeValidationError",
    "EdcmMetapatBridgeRecord", "InformationLossRecord",
    "RetainedLayerDigest", "PROFILE_OPTIONS",
    "EdcmMetapatOrderedOccurrenceProfile", "ProfileBoundStructure",
]
